apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      initContainers:
      - name: wait-for-auth
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z auth-service 8001; do echo waiting for auth-service; sleep 2; done;']
      - name: wait-for-todo
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z todo-service 8000; do echo waiting for todo-service; sleep 2; done;']
      containers:
      - name: api-gateway
        image: asaadballa/api-gateway:latest  
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:8001"  
        - name: TODO_SERVICE_URL
          value: "http://todo-service:8000"  
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP