apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-service
  template:
    metadata:
      labels:
        app: todo-service
    spec:
      containers:
      - name: todo-service
        image: asaadballa/todo-service:latest
        ports:
        - containerPort: 8001
        env:
        - name: PORT
          value: "8001"
---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  selector:
    app: todo-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP