# PostgreSQL Configuration for Auth Service
global:
  postgresql:
    auth:
      username: "authuser"
      password: "authpassword"
      database: "authdb"
      
primary:
  # Persistence configuration
  persistence:
    enabled: true
    storageClass: "" # Use default storage class
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    annotations: {}
    
  # Resource limits
  resources:
    limits:
      memory: 512Mi
      cpu: 500m
    requests:
      memory: 256Mi
      cpu: 250m
      
  # Pod security context
  podSecurityContext:
    enabled: true
    fsGroup: 1001
    
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsNonRoot: true
    
  # Health checks
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
    
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1

# Service configuration
service:
  type: ClusterIP
  ports:
    postgresql: 5432
    
# Network policy (optional)
networkPolicy:
  enabled: false
  
# Metrics (optional)
metrics:
  enabled: false
  
# Backup configuration (optional)
backup:
  enabled: false